// Copyright (c) 2026 Said Arturo Lopez. MIT License.
// MarkdownEmoji.swift - Emoji shortcode lookup for inline markdown parsing.

import Foundation

enum MarkdownEmoji {
    private static let table: [String: String] = [
        "+1": "👍",
        "-1": "👎",
        "100": "💯",
        "arrow_down": "⬇️",
        "arrow_left": "⬅️",
        "arrow_right": "➡️",
        "arrow_up": "⬆️",
        "art": "🎨",
        "beers": "🍻",
        "bell": "🔔",
        "bookmark": "🔖",
        "boom": "💥",
        "bug": "🐛",
        "bulb": "💡",
        "calendar": "📆",
        "camera": "📷",
        "checkered_flag": "🏁",
        "clap": "👏",
        "clipboard": "📋",
        "clock1": "🕐",
        "closed_lock_with_key": "🔐",
        "coffee": "☕",
        "computer": "💻",
        "confetti_ball": "🎊",
        "construction": "🚧",
        "cry": "😢",
        "eyes": "👀",
        "fire": "🔥",
        "fix": "🛠️",
        "gem": "💎",
        "gift": "🎁",
        "globe_with_meridians": "🌐",
        "hammer": "🔨",
        "heart": "❤️",
        "heavy_check_mark": "✔️",
        "hourglass": "⏳",
        "information_source": "ℹ️",
        "key": "🔑",
        "label": "🏷️",
        "large_blue_circle": "🔵",
        "large_green_circle": "🟢",
        "large_orange_diamond": "🔶",
        "large_red_square": "🟥",
        "large_yellow_circle": "🟡",
        "link": "🔗",
        "lock": "🔒",
        "mag": "🔍",
        "memo": "📝",
        "moon": "🌙",
        "no_entry": "⛔",
        "package": "📦",
        "paperclip": "📎",
        "pencil2": "✏️",
        "point_right": "👉",
        "question": "❓",
        "rocket": "🚀",
        "rotating_light": "🚨",
        "satellite": "📡",
        "seedling": "🌱",
        "ship": "🚢",
        "sparkles": "✨",
        "star": "⭐",
        "sunny": "☀️",
        "tada": "🎉",
        "test_tube": "🧪",
        "thought_balloon": "💭",
        "thumbsup": "👍",
        "thumbsdown": "👎",
        "ticket": "🎫",
        "triangular_flag_on_post": "🚩",
        "unlock": "🔓",
        "warning": "⚠️",
        "wave": "👋",
        "wrench": "🔧",
        "x": "❌",
        "zap": "⚡",
        "smile": "😄",
        "grin": "😁",
        "joy": "😂",
        "wink": "😉",
        "thinking": "🤔",
        "sunglasses": "😎",
        "partying_face": "🥳",
        "sob": "😭",
        "frowning": "😦",
        "angry": "😠",
        "neutral_face": "😐",
        "robot": "🤖",
        "waveform": "〰️",
        "white_check_mark": "✅"
    ]

    static func resolve(_ shortcode: String) -> String? {
        table[shortcode]
    }
}
