// Copyright (c) 2026 Said Arturo Lopez. MIT License.
// NotificationManaging.swift - Contract for the centralized notification manager.

import Foundation
import Combine

// MARK: - Notification Managing Protocol

/// Centralized notification manager for both in-app and macOS system notifications.
///
/// Receives events from the `AgentDetectionEngine` and other modules, decides
/// what to notify based on user configuration, manages unread state per tab,
/// and coordinates macOS push notifications via `UNUserNotificationCenter`.
///
/// Uses Combine publishers (ADR-003) because multiple observers need to react
/// to notification changes (tab bar badges, dock icon, menu bar, etc.).
///
/// Rate limiting: Coalesces notifications to avoid spamming the user.
/// At most one notification per tab per event type within a configurable
/// time window (default: 5 seconds).
///
/// - SeeAlso: ADR-003 (State management)
/// - SeeAlso: ARCHITECTURE.md Section 7.3
@MainActor
protocol NotificationManaging: AnyObject {

    /// Sends a notification through the notification pipeline.
    ///
    /// The manager decides whether to show a macOS notification, update
    /// the tab badge, or both, based on user configuration and rate limiting.
    /// - Parameter notification: The notification to process.
    func notify(_ notification: CocxyNotification)

    /// Marks all notifications for a tab as read.
    ///
    /// Typically called when the user focuses a tab.
    /// - Parameter tabId: The tab whose notifications should be marked as read.
    func markAsRead(tabId: TabID)

    /// Marks all notifications across all tabs as read.
    func markAllAsRead()

    /// Returns the ID of the next tab with unread notifications.
    ///
    /// Tabs are ordered by urgency: `agentNeedsAttention` > `agentError`
    /// > `agentFinished` > `processExited` > `custom`.
    /// Returns `nil` if there are no unread notifications.
    ///
    /// - Returns: The `TabID` of the next tab needing attention, or `nil`.
    func gotoNextUnread() -> TabID?

    /// Total number of unread notifications across all tabs.
    var unreadCount: Int { get }

    /// Publisher that emits every new notification as it arrives.
    ///
    /// Consumers can use this to update badges, flash tabs, etc.
    var notificationsPublisher: AnyPublisher<CocxyNotification, Never> { get }

    /// Publisher that emits the current unread count whenever it changes.
    var unreadCountPublisher: AnyPublisher<Int, Never> { get }
}

// MARK: - Notification Model

/// A notification generated by Cocxy.
///
/// Notifications are created by the domain layer (e.g., agent detection engine)
/// and flow through the `NotificationManaging` pipeline to reach the UI and
/// macOS notification center.
struct CocxyNotification: Identifiable, Sendable {
    /// Unique identifier for this notification.
    let id: UUID
    /// The type of event that triggered this notification.
    let type: NotificationType
    /// The tab this notification is associated with.
    let tabId: TabID
    /// Short title displayed in the notification banner.
    let title: String
    /// Detailed body text.
    let body: String
    /// When the notification was created.
    let timestamp: Date
    /// Whether the user has acknowledged this notification.
    var isRead: Bool

    init(
        id: UUID = UUID(),
        type: NotificationType,
        tabId: TabID,
        title: String,
        body: String,
        timestamp: Date = Date(),
        isRead: Bool = false
    ) {
        self.id = id
        self.type = type
        self.tabId = tabId
        self.title = title
        self.body = body
        self.timestamp = timestamp
        self.isRead = isRead
    }
}

// MARK: - Notification Type

/// Categories of notifications that Cocxy can generate.
///
/// Ordered by urgency (highest first) for the "goto next unread" feature.
enum NotificationType: Sendable {
    /// The agent is waiting for user input (highest urgency).
    case agentNeedsAttention
    /// The agent encountered an error.
    case agentError
    /// The agent finished its task.
    case agentFinished
    /// The shell process exited with the given exit code.
    case processExited(code: Int32)
    /// A custom notification sent via the CLI companion (`cocxy notify`).
    case custom(String)
}

// MARK: - NotificationType + Comparable (urgency ordering)

extension NotificationType: Comparable {
    /// Urgency level used for ordering. Lower number = higher urgency.
    private var urgencyLevel: Int {
        switch self {
        case .agentNeedsAttention: return 0
        case .agentError: return 1
        case .agentFinished: return 2
        case .processExited: return 3
        case .custom: return 4
        }
    }

    static func < (lhs: NotificationType, rhs: NotificationType) -> Bool {
        lhs.urgencyLevel < rhs.urgencyLevel
    }
}
