// Copyright (c) 2026 Said Arturo Lopez. MIT License.
// TimelineEvent.swift - Domain models for the agent timeline.

import Foundation

// MARK: - Timeline Event Type

/// Types of events that appear in the agent timeline.
///
/// Rich events come from Layer 0 hooks (toolUse, toolFailure, userPrompt, etc.).
/// Degraded events from layers 1-3 use `stateChange` with summary-only data.
///
/// - SeeAlso: ADR-008 Section 5.2 (Timeline Event Types)
enum TimelineEventType: String, Codable, Sendable, CaseIterable {
    /// Agent session started (from hooks SessionStart).
    case sessionStart
    /// Agent session ended (from hooks SessionEnd).
    case sessionEnd
    /// Successful tool invocation (PreToolUse + PostToolUse combined).
    case toolUse
    /// Failed tool invocation (PostToolUseFailure).
    case toolFailure
    /// User submitted a prompt (UserPromptSubmit).
    case userPrompt
    /// Agent response / stop (Stop event).
    case agentResponse
    /// A subagent was spawned (SubagentStart).
    case subagentStart
    /// A subagent stopped (SubagentStop).
    case subagentStop
    /// Notification from the agent (Notification).
    case notification
    /// A task was completed (TaskCompleted).
    case taskCompleted
    /// Generic state change from pattern/timing detection (fallback for non-hook agents).
    case stateChange
}

// MARK: - Timeline Event

/// A single event in the agent timeline.
///
/// Timeline events are append-only records of what an agent did during a session.
/// Each event has a timestamp, type, session ID, and a human-readable summary.
///
/// Rich events from Layer 0 hooks include tool name, file path, and duration.
/// Degraded events from layers 1-3 only have a summary description.
///
/// ## Memory Budget
///
/// Max 1000 events per session (FIFO eviction). Each event is approximately
/// 200-500 bytes. At 1000 events per session, that is ~500KB per session,
/// well within the 5 MB per agent budget from ADR-008.
///
/// - SeeAlso: ADR-008 Section 5.2 (TimelineEvent)
/// - SeeAlso: HU-108 (Agent Timeline)
struct TimelineEvent: Identifiable, Codable, Sendable, Equatable {
    /// Unique identifier for this event (generated by Cocxy).
    let id: UUID

    /// When the event occurred.
    let timestamp: Date

    /// The type of timeline event.
    let type: TimelineEventType

    /// Claude Code session ID that this event belongs to.
    let sessionId: String

    /// The window that owned the originating tab when the event was captured.
    let windowID: WindowID?

    /// Human-readable window label for UI display.
    let windowLabel: String?

    /// Tool name if applicable (e.g., "Write", "Read", "Bash", "Edit").
    let toolName: String?

    /// File path affected by the event, if applicable.
    let filePath: String?

    /// Human-readable summary for display (e.g., "Write: Sources/App.swift").
    let summary: String

    /// Duration of the event in milliseconds, if available.
    let durationMs: Int?

    /// Whether this event represents an error condition.
    let isError: Bool

    /// Creates a new timeline event with all fields.
    ///
    /// - Parameters:
    ///   - id: Unique identifier. Defaults to a new UUID.
    ///   - timestamp: When the event occurred. Defaults to now.
    ///   - type: The type of timeline event.
    ///   - sessionId: Session this event belongs to.
    ///   - toolName: Tool name, if applicable.
    ///   - filePath: Affected file path, if applicable.
    ///   - summary: Human-readable description.
    ///   - durationMs: Duration in milliseconds, if available.
    ///   - isError: Whether this is an error event.
    init(
        id: UUID = UUID(),
        timestamp: Date = Date(),
        type: TimelineEventType,
        sessionId: String,
        windowID: WindowID? = nil,
        windowLabel: String? = nil,
        toolName: String? = nil,
        filePath: String? = nil,
        summary: String,
        durationMs: Int? = nil,
        isError: Bool = false
    ) {
        self.id = id
        self.timestamp = timestamp
        self.type = type
        self.sessionId = sessionId
        self.windowID = windowID
        self.windowLabel = windowLabel
        self.toolName = toolName
        self.filePath = filePath
        self.summary = summary
        self.durationMs = durationMs
        self.isError = isError
    }

    /// Converts a `HookEvent` to a `TimelineEvent` for the timeline store.
    ///
    /// Centralizes the mapping logic so both `AppDelegate` and any future
    /// wiring point can convert hook events consistently.
    static func from(
        hookEvent: HookEvent,
        windowID: WindowID? = nil,
        windowLabel: String? = nil
    ) -> TimelineEvent {
        let eventType: TimelineEventType
        var toolName: String?
        var filePath: String?
        var summary: String
        var isError = false

        switch hookEvent.type {
        case .sessionStart:
            eventType = .sessionStart
            summary = "Session started"
            if case .sessionStart(let data) = hookEvent.data {
                if let agent = data.agentType {
                    summary = "Session started: \(agent)"
                }
            }

        case .sessionEnd:
            eventType = .sessionEnd
            summary = "Session ended"

        case .stop:
            eventType = .agentResponse
            summary = "Agent stopped"
            if case .stop(let data) = hookEvent.data {
                summary = data.lastMessage ?? "Agent stopped"
            }

        case .preToolUse, .postToolUse:
            eventType = .toolUse
            if case .toolUse(let data) = hookEvent.data {
                toolName = data.toolName
                filePath = data.toolInput?["file_path"] ?? data.toolInput?["path"]
                summary = filePath.map { "\(data.toolName): \($0)" } ?? data.toolName
            } else {
                summary = "Tool use"
            }

        case .postToolUseFailure:
            eventType = .toolFailure
            isError = true
            if case .toolUse(let data) = hookEvent.data {
                toolName = data.toolName
                summary = "Error: \(data.error ?? data.toolName)"
            } else {
                summary = "Tool failure"
            }

        case .subagentStart:
            eventType = .subagentStart
            summary = "Subagent started"
            if case .subagent(let data) = hookEvent.data {
                summary = "Subagent started: \(data.subagentType ?? data.subagentId)"
            }

        case .subagentStop:
            eventType = .subagentStop
            summary = "Subagent stopped"

        case .notification:
            eventType = .notification
            summary = "Notification"
            if case .notification(let data) = hookEvent.data {
                summary = data.title ?? "Notification"
            }

        case .userPromptSubmit:
            eventType = .userPrompt
            summary = "User prompt submitted"

        case .teammateIdle:
            eventType = .stateChange
            summary = "Teammate idle"

        case .taskCompleted:
            eventType = .taskCompleted
            summary = "Task completed"
            if case .taskCompleted(let data) = hookEvent.data {
                summary = data.taskDescription ?? "Task completed"
            }

        case .cwdChanged:
            // Surface CWD changes in the timeline so users can trace when
            // Claude Code moved into a new directory. The CWD itself lives on
            // HookEvent.cwd; previousCwd adds context when available.
            eventType = .stateChange
            if let currentCwd = hookEvent.cwd, !currentCwd.isEmpty {
                if case .cwdChanged(let data) = hookEvent.data,
                   let previous = data.previousCwd, !previous.isEmpty {
                    summary = "Changed directory: \(previous) -> \(currentCwd)"
                } else {
                    summary = "Changed directory: \(currentCwd)"
                }
            } else {
                summary = "Working directory changed"
            }

        case .fileChanged:
            // Filesystem mutations surface as stateChange rows, keeping the
            // native filePath column populated so the UI can link to the file.
            eventType = .stateChange
            if case .fileChanged(let data) = hookEvent.data, !data.filePath.isEmpty {
                filePath = data.filePath
                let fileName = URL(fileURLWithPath: data.filePath).lastPathComponent
                if let change = data.changeType?.trimmingCharacters(in: .whitespaces), !change.isEmpty {
                    summary = "File \(change): \(fileName)"
                } else {
                    summary = "File changed: \(fileName)"
                }
            } else {
                summary = "File changed"
            }
        }

        return TimelineEvent(
            timestamp: hookEvent.timestamp,
            type: eventType,
            sessionId: hookEvent.sessionId,
            windowID: windowID,
            windowLabel: windowLabel,
            toolName: toolName,
            filePath: filePath,
            summary: summary,
            durationMs: nil,
            isError: isError
        )
    }
}
