// Copyright (c) 2026 Said Arturo Lopez. MIT License.
// RelayToken.swift - HMAC-SHA256 token for relay channel authentication.

import Foundation
import CryptoKit

// MARK: - Relay Token

/// Authentication token for relay channels using HMAC-SHA256.
///
/// Each channel has its own token with a 32-byte random secret.
/// The token is used to sign and validate handshake payloads in
/// the `RelayAuthBroker` wire protocol.
///
/// ## Security Properties
///
/// - Secret generated by CryptoKit's system-backed CSPRNG.
/// - HMAC-SHA256 provides authentication and integrity.
/// - Rotation generates a fresh secret, invalidating all prior signatures.
/// - Tokens are stored in Keychain (via `RelayKeychainStore`), never in plain text.
struct RelayToken: Codable, Sendable {

    /// 32-byte random secret for HMAC computation.
    let secret: Data

    /// Generates a new token with a cryptographically random 32-byte secret.
    static func generate() -> RelayToken {
        let key = SymmetricKey(size: .bits256)
        return RelayToken(secret: key.withUnsafeBytes { Data($0) })
    }

    /// Signs a payload using HMAC-SHA256 with this token's secret.
    ///
    /// - Parameter payload: The data to authenticate.
    /// - Returns: A 32-byte HMAC signature.
    func sign(_ payload: Data) -> Data {
        let key = SymmetricKey(data: secret)
        let mac = HMAC<SHA256>.authenticationCode(for: payload, using: key)
        return Data(mac)
    }

    /// Validates an HMAC signature against a payload.
    ///
    /// Uses constant-time comparison to prevent timing attacks.
    ///
    /// - Parameters:
    ///   - payload: The original data that was signed.
    ///   - signature: The HMAC signature to verify.
    /// - Returns: `true` if the signature is valid for the given payload.
    func validate(payload: Data, signature: Data) -> Bool {
        let expected = sign(payload)
        guard expected.count == signature.count else { return false }
        var diff: UInt8 = 0
        for (lhs, rhs) in zip(expected, signature) {
            diff |= lhs ^ rhs
        }
        return diff == 0
    }

    /// Creates a new token with a fresh secret, invalidating this one.
    ///
    /// The old token's signatures will no longer validate against the
    /// new token's secret.
    func rotated() -> RelayToken {
        RelayToken.generate()
    }
}

// MARK: - Replay Tracker

/// Tracks authenticated nonces to prevent replay attacks.
///
/// Maintains a set of recently seen timestamps within a configurable
/// time window. Timestamps outside the window (past or future) are
/// rejected immediately. Timestamps already seen within the window
/// are also rejected.
struct ReplayTracker: Sendable {

    /// Maximum age of a valid timestamp (in seconds from now).
    let windowSeconds: Int
    let maxEntries: Int

    /// Nonces seen within the current freshness window, keyed to their timestamps.
    private var seenNonces: [Data: UInt64] = [:]

    init(windowSeconds: Int = 60, maxEntries: Int = 4096) {
        self.windowSeconds = max(0, windowSeconds)
        self.maxEntries = max(1, maxEntries)
    }

    /// Checks if a timestamp is fresh and its nonce has not been replayed.
    ///
    /// - Parameters:
    ///   - timestamp: Unix epoch seconds.
    ///   - nonce: Random authenticated nonce for this connection.
    /// - Returns: `true` if the timestamp is within the window and hasn't been seen.
    mutating func isAllowed(timestamp: UInt64, nonce: Data) -> Bool {
        guard nonce.count == RelayHandshake.nonceSize else { return false }
        let now = UInt64(Date().timeIntervalSince1970)
        let windowU64 = UInt64(windowSeconds)

        let distance = timestamp > now ? timestamp - now : now - timestamp
        guard distance <= windowU64 else { return false }

        pruneOldNonces(now: now)

        // Reject replayed nonces while allowing legitimate same-second connections.
        guard seenNonces[nonce] == nil else { return false }
        guard seenNonces.count < maxEntries else { return false }

        seenNonces[nonce] = timestamp
        return true
    }

    /// Removes nonces whose authenticated timestamp has fallen outside the window.
    private mutating func pruneOldNonces(now: UInt64) {
        let windowU64 = UInt64(windowSeconds)
        let cutoff = now > windowU64 ? now - windowU64 : 0
        seenNonces = seenNonces.filter { $0.value >= cutoff }
    }
}
